<html>
    <head>
        <title>Tugas Praktikum</title>
        <link rel="stylesheet" href="https://s0.bukalapak.com/ast/bazaar-dweb/base/bazaar@2.38.0.css"><link rel="stylesheet" crossorigin="anonymous" href="https://s0.bukalapak.com/marketplace/application-v2-9db8b3d8b53d35ac7c56.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" crossorigin="anonymous" href="https://s0.bukalapak.com/marketplace/application-v2-9db8b3d8b53d35ac7c56.css"></noscript><script src="https://s0.bukalapak.com/marketplace/polyfills-9db8b3d8b53d35ac7c56.js" defer=""></script><script src="https://s0.bukalapak.com/marketplace/vnd-9db8b3d8b53d35ac7c56.js" defer=""></script><script src="https://s0.bukalapak.com/marketplace/summoner-9db8b3d8b53d35ac7c56.js" defer=""></script><script src="https://s0.bukalapak.com/marketplace/app-9db8b3d8b53d35ac7c56.js" defer=""></script><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer', 'GTM-THDD63');</script><link href="https://assets.bukalapak.com/sigil/assets/fragments-white-header-dweb-v2-index-1e62857c82075818cd4e.css" rel="stylesheet" type="text/css"><script src="https://assets.bukalapak.com/sigil/assets/fragments-white-header-dweb-v2-index-1e62857c82075818cd4e.js" crossorigin defer></script><link href="https://s0.bukalapak.com/baseplate/assets/fragments-home-atf-index-8c7d64daef9475f6d486.css" rel="stylesheet" type="text/css"><script src="https://s0.bukalapak.com/baseplate/assets/fragments-home-atf-index-8c7d64daef9475f6d486.js" crossorigin defer></script><link href="https://s0.bukalapak.com/baseplate/assets/fragments-home-section-index-8c7d64daef9475f6d486.css" rel="stylesheet" type="text/css"><script src="https://s0.bukalapak.com/baseplate/assets/fragments-home-section-index-8c7d64daef9475f6d486.js" crossorigin defer></script><script src="https://s0.bukalapak.com/baseplate/assets/fragments-popular-search-index-8c7d64daef9475f6d486.js" crossorigin defer></script><link href="https://s0.bukalapak.com/baseplate/assets/fragments-popular-links-index-8c7d64daef9475f6d486.css" rel="stylesheet" type="text/css"><script src="https://s0.bukalapak.com/baseplate/assets/fragments-popular-links-index-8c7d64daef9475f6d486.js" crossorigin defer></script><script src="https://s0.bukalapak.com/baseplate/assets/fragments-page-description-index-8c7d64daef9475f6d486.js" crossorigin defer></script></head><body class="layout has-fixed-header--white-header" data-no-turbolink=""><script type="application/ld+json">{"@context":"https://schema.org","@type":"Organization","name":"Bukalapak","url":"https://www.bukalapak.com","sameAs":["https://www.facebook.com/bukalapak","https://twitter.com/bukalapak","https://instagram.com/bukalapak","https://www.youtube.com/user/bukalapak","https://www.pinterest.com/bukalapakdotcom"],"logo":"https://www.bukalapak.com/images/logo-google-graph.png"}</script><script type="application/ld+json">{"@context":"https://schema.org","@type":"WebSite","name":"Bukalapak","alternateName":"BL","url":"https://www.bukalapak.com"}</script>

    </head>
        <body>
        <div class="row">
        <div id="homepage-home-section" data-server-rendered="true"><div id="homepage-home-section-app" class="u-bg--white"><section class="bl-section dope-section mt-48"><div class="bl-container"><!----><div class="qa-dope-container bl-dope-container"><!----> <div class="bl-dope-container__wrapper"><div class="bl-dope-container__head"><div class="bl-dope-container__head-content" style="padding-right:0;padding-left:0;padding-top:0;padding-bottom:0;"><!----> <div class="bl-flex-container mb-0 bl-dope-container__grid-wrapper"><div class="bl-flex-item mt-16 mb-16 bl-dope-container__grid-item" style="flex:0 1 100%;"><a href="https://www.bukalapak.com/super-seller?referrer=recommendation&amp;from=homepage-menu-1" class="bl-dope-item bl-dope-item--medium"><div class="bl-dope-item__body"><!----> <!----> <!----> <img src="https://s4.bukalapak.com/athena/1606361301726/original/hp_menu_icon_6ff40e16-7e1b-4fb2-881f-0ac9c4cc1113.jpg" alt="Bukalapak"></div> <div class="bl-dope-item__footer"><!----> <!----> <p class="bl-text bl-text--body-default bl-text--semi-bold bl-text--ellipsis__2">
            Super Seller
          </p></div></a></div><div class="bl-flex-item mt-16 mb-16 bl-dope-container__grid-item" style="flex:0 1 100%;"><a href="https://www.bukalapak.com/bukaemas?referrer=recommendation&amp;from=homepage-menu-2" class="bl-dope-item bl-dope-item--medium"><div class="bl-dope-item__body"><!----> <!----> <!----> <img src="https://s3.bukalapak.com/dope/1581554929544/original/hp_menu_icon_c74c441a-fa86-42d8-b7ea-3420cde532ec.jpg" alt="Bukalapak"></div> <div class="bl-dope-item__footer"><!----> <!----> <p class="bl-text bl-text--body-default bl-text--semi-bold bl-text--ellipsis__2">
            BukaEmas
          </p></div></a></div><div class="bl-flex-item mt-16 mb-16 bl-dope-container__grid-item" style="flex:0 1 100%;"><a href="https://m.bukalapak.com/promo-campaign/bazar-diskon-heboh?referrer=recommendation&amp;from=homepage-menu-3" class="bl-dope-item bl-dope-item--medium"><div class="bl-dope-item__body"><!----> <!----> <!----> <img src="https://s4.bukalapak.com/athena/1593141004812/original/hp_menu_icon_fb9007d5-ca33-47bf-b384-6e325fbd6bef.jpg" alt="Bukalapak"></div> <div class="bl-dope-item__footer"><!----> <!----> <p class="bl-text bl-text--body-default bl-text--semi-bold bl-text--ellipsis__2">
            Bazar s.d 90%
          </p></div></a></div><div class="bl-flex-item mt-16 mb-16 bl-dope-container__grid-item" style="flex:0 1 100%;"><a href="https://www.bukalapak.com/pulsa?referrer=recommendation&amp;from=homepage-menu-4" class="bl-dope-item bl-dope-item--medium"><div class="bl-dope-item__body"><!----> <!----> <!----> <img src="https://s2.bukalapak.com/dope/1581555601589/original/hp_menu_icon_f28ec829-40fd-4dbd-9ef3-7d491cfc3e5a.jpg" alt="Bukalapak"></div> <div class="bl-dope-item__footer"><!----> <!----> <p class="bl-text bl-text--body-default bl-text--semi-bold bl-text--ellipsis__2">
            Pulsa Prabayar
          </p></div></a></div><div class="bl-flex-item mt-16 mb-16 bl-dope-container__grid-item" style="flex:0 1 100%;"><a href="https://www.bukalapak.com/paket-data?referrer=recommendation&amp;from=homepage-menu-5" class="bl-dope-item bl-dope-item--medium"><div class="bl-dope-item__body"><!----> <!----> <!----> <img src="https://s2.bukalapak.com/dope/1581555577452/original/hp_menu_icon_82b331ed-a7b4-4959-9cbc-9df5a94c5e9a.jpg" alt="Bukalapak"></div> <div class="bl-dope-item__footer"><!----> <!----> <p class="bl-text bl-text--body-default bl-text--semi-bold bl-text--ellipsis__2">
            Paket Data
          </p></div></a></div><div class="bl-flex-item mt-16 mb-16 bl-dope-container__grid-item" style="flex:0 1 100%;"><a href="https://www.bukalapak.com/voucher-game?referrer=recommendation&amp;from=homepage-menu-6" class="bl-dope-item bl-dope-item--medium"><div class="bl-dope-item__body"><!----> <!----> <!----> <img src="https://s2.bukalapak.com/dope/1581555568239/original/hp_menu_icon_b3f21cd5-db80-468e-8209-db5fdfa6a694.jpg" alt="Bukalapak"></div> <div class="bl-dope-item__footer"><!----> <!----> <p class="bl-text bl-text--body-default bl-text--semi-bold bl-text--ellipsis__2">
            Voucher Game
          </p></div></a></div><div class="bl-flex-item mt-16 mb-16 bl-dope-container__grid-item" style="flex:0 1 100%;"><a href="https://www.bukalapak.com/listrik-pln/token-listrik?referrer=recommendation&amp;from=homepage-menu-7" class="bl-dope-item bl-dope-item--medium"><div class="bl-dope-item__body"><!----> <!----> <!----> <img src="https://s0.bukalapak.com/dope/1581555557556/original/hp_menu_icon_bf558f5e-17c0-4e49-a0a0-5aa55801fba0.jpg" alt="Bukalapak"></div> <div class="bl-dope-item__footer"><!----> <!----> <p class="bl-text bl-text--body-default bl-text--semi-bold bl-text--ellipsis__2">
            Token Listrik
          </p></div></a></div><div class="bl-flex-item mt-16 mb-16 bl-dope-container__grid-item" style="flex:0 1 100%;"><a href="https://bukalapak.com/kartu-prakerja?source=dope&amp;referrer=recommendation&amp;from=homepage-menu-8" class="bl-dope-item bl-dope-item--medium"><div class="bl-dope-item__body"><!----> <!----> <!----> <img src="https://s4.bukalapak.com/athena/1587561193329/original/hp_menu_icon_6777cc70-663f-47f0-8431-a8c78fcebe68.jpg" alt="Bukalapak"></div> <div class="bl-dope-item__footer"><!----> <!----> <p class="bl-text bl-text--body-default bl-text--semi-bold bl-text--ellipsis__2">
            Kartu Prakerja
          </p></div></a></div> <div class="bl-flex-item mb-16 mt-16 bl-dope-container__grid-item" style="flex:0 1 100%;cursor:pointer;"><div class="bl-dope-container__dope-trigger"><div class="bl-dope-container__dope-trigger-body"><!----> <!----> <div class="bl-dope-container__dope-trigger-content"><svg version="1.1" viewBox="0 0 20 20" class="svg-icon svg-fill" style="width:24px;height:24px;"><path fill="#81868f" stroke="none" pid="0" fill-rule="evenodd" clip-rule="evenodd" d="M17 16v-4a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1zm-8 0v-4a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1zm8-8V4a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1zM8 9H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1z" _fill="#000"/></svg></div></div> <div class="bl-dope-container__dope-trigger-footer"><!----> <!----> <p class="bl-text bl-text--body-default bl-text--semi-bold bl-text--ellipsis__2">
            Semua Menu
        </div>
        <div class="row">
            </p></div></div></div></div></div> <!----></div> <!----> <!----></div></div></div></section><section class="bl-section promo-section mt-48"><div class="bl-container"><div class="bl-image-group qa-todays-promo-card"><div class="bl-flex-container is-gutter-20"><div class="bl-flex-item bl-image-group__item" style="flex:0 1 100%;max-width:16.666666666666668%;"><!----> <!----> <!----> <a href="https://www.bukalapak.com/promo-campaign/diskon-ppkm?from=brand-homepage-1" target="" class="bl-image-group__wrapper"><div class="bl-image-group__head"><!----> <img src="https://s4.bukalapak.com/rev-banner/flash_banner/860652341/s-264-264/mobile_DiskonPPKM_eced8f68-b4b1-4dd8-b51d-12627e22a4dc.jpeg" alt="Diskon PPKM" class="bl-image-group__img"></div> <div class="bl-image-group__body"><p class="bl-text bl-text--subheading-3 bl-text--ellipsis__2">
            Diskon PPKM
            </p></div></a></div><div class="bl-flex-item bl-image-group__item" style="flex:0 1 100%;max-width:16.666666666666668%;"><!----> <!----> <!----> <a href="https://www.bukalapak.com/promo-campaign/murah-mantap-september?from=brand-homepage-2" target="" class="bl-image-group__wrapper"><div class="bl-image-group__head"><!----> <img src="https://s4.bukalapak.com/rev-banner/flash_banner/585356984/s-264-264/mobile_MurahMantap_8bbb144e-9121-4802-9fcf-9a60f44add3c.jpeg" alt="Murah Mantap" class="bl-image-group__img"></div> <div class="bl-image-group__body"><p class="bl-text bl-text--subheading-3 bl-text--ellipsis__2">
            Murah Mantap
            </p></div></a></div><div class="bl-flex-item bl-image-group__item" style="flex:0 1 100%;max-width:16.666666666666668%;"><!----> <!----> <!----> <a href="https://www.bukalapak.com/promo-campaign/elektrophone-sale-september?from=brand-homepage-3" target="" class="bl-image-group__wrapper"><div class="bl-image-group__head"><!----> <img src="https://s4.bukalapak.com/rev-banner/flash_banner/958633355/s-264-264/mobile_ElektrophoneSale_cf1b3137-cb11-4190-870b-6ade5803dac8.jpeg" alt="Elektrophone Sale" class="bl-image-group__img"></div> <div class="bl-image-group__body"><p class="bl-text bl-text--subheading-3 bl-text--ellipsis__2">
            Elektrophone Sale
            </p></div></a></div><div class="bl-flex-item bl-image-group__item" style="flex:0 1 100%;max-width:16.666666666666668%;"><!----> <!----> <!----> <a href="https://www.bukalapak.com/promo-campaign/fashion-festival-september?from=brand-homepage-4" target="" class="bl-image-group__wrapper"><div class="bl-image-group__head"><!----> <img src="https://s4.bukalapak.com/rev-banner/flash_banner/348980120/s-264-264/mobile_FashionFestival_8f211f94-700a-480b-9e08-1ffaafcdee6a.jpeg" alt="Fashion Festival" class="bl-image-group__img"></div> <div class="bl-image-group__body"><p class="bl-text bl-text--subheading-3 bl-text--ellipsis__2">
            Fashion Festival
            </p></div></a></div><div class="bl-flex-item bl-image-group__item" style="flex:0 1 100%;max-width:16.666666666666668%;"><!----> <!----> <!----> <a href="https://www.bukalapak.com/promo-campaign/jagoan-gaming?referrer=promo-hari-ini&amp;from=brand-homepage-5" target="" class="bl-image-group__wrapper"><div class="bl-image-group__head"><!----> <img src="https://s4.bukalapak.com/rev-banner/flash_banner/332663128/s-264-264/mobile_JagoanGaming_98881e51-2ebf-4baf-9c91-b23e14882eab.jpeg" alt="Jagoan Gaming" class="bl-image-group__img"></div> <div class="bl-image-group__body"><p class="bl-text bl-text--subheading-3 bl-text--ellipsis__2">
            Jagoan Gaming
            </p></div></a></div><div class="bl-flex-item bl-image-group__item" style="flex:0 1 100%;max-width:16.666666666666668%;"><!----> <!----> <!----> <a href="https://www.bukalapak.com/promo-campaign/flash-diskon?from=brand-homepage-6" target="" class="bl-image-group__wrapper"><div class="bl-image-group__head"><!----> <img src="https://s4.bukalapak.com/rev-banner/flash_banner/158940117/s-264-264/mobile_FlashDiskon_51c681a8-254b-4bb4-8b63-3808b5987a05.jpeg" alt="Flash Diskon" class="bl-image-group__img"></div> <div class="bl-image-group__body"><p class="bl-text bl-text--subheading-3 bl-text--ellipsis__2">
            Flash Diskon
        </div>
        <section class="b1-section qa-nuzone-banner mt-48"><div class="b1-container><a href="/promo-campaign/zona-pengguna-baru">
            <picture>
                <img src="https://s0.bukalapak.com/athena/new-zone/s-2180-280/nuz_dweb.jpeg.webp" alt="new-user-zone-banner" style="width: 100%; ">
            </picture>
            </a>
        </section>
        </body>
